### ISSUE TITLE
About pacbio's raw reads

### ISSUE THREAD

**Issue by YilinZhang449** [HuffordLab/NAM-genomes#13]
Hello,
I'm a little confused, is the pacbio sequencing here generating CLR data or CCS data? How many G base of sequencing data per sample on average?

Thank you!

**Comment by aseetharam** [comment]
Hello @YilinZhang449,

We used PacBio reads. Specifically, CLR data (Subreads) was used. Please see [PacBio_stats_v2.1_NAM_genomes.xlsx](https://github.com/HuffordLab/NAM-genomes/files/7878064/PacBio_stats_v2.1_NAM_genomes.xlsx) spreadsheet for details regarding coverage. 

Thanks,

**Comment by ttian627** [comment]
> Hello @YilinZhang449,
> 
> We used PacBio reads. Specifically, CLR data (Subreads) was used. Please see [PacBio_stats_v2.1_NAM_genomes.xlsx](https://github.com/HuffordLab/NAM-genomes/files/7878064/PacBio_stats_v2.1_NAM_genomes.xlsx) spreadsheet for details regarding coverage.
> 
> Thanks,

Hello,

What's the meaning of "processed" at subreads, it seems all the pacbio CLRs passed the QC step by SequelTools.

Thank you

Tian

**Comment by DavidEHufnagel** [comment]
Hello,

SequelTools calculates many statistics of sequence quantity and quality and
assembles CLRs in order to do so. However, SequelTools does not generate or
work with CCS data.

Best, David

**Comment by aseetharam** [comment]
> > Hello @YilinZhang449,
> > We used PacBio reads. Specifically, CLR data (Subreads) was used. Please see [PacBio_stats_v2.1_NAM_genomes.xlsx](https://github.com/HuffordLab/NAM-genomes/files/7878064/PacBio_stats_v2.1_NAM_genomes.xlsx) spreadsheet for details regarding coverage.
> > Thanks,
> 
> Hello,
> 
> What's the meaning of "processed" at subreads, it seems all the pacbio CLRs passed the QC step by SequelTools.
> 
> Thank you
> 
> Tian

Also, if you're referring to the spreadsheet headers, they are simplified terms for users to help understand what they are looking at: Polymerase Reads (**raw**) vs. Sub Reads (**processed**). As mentioned in the methods (supplementary), no processing was performed on subreads other than error correction itself. 

Thanks,

**Comment by ttian627** [comment]
> > Hello @YilinZhang449,
> > We used PacBio reads. Specifically, CLR data (Subreads) was used. Please see [PacBio_stats_v2.1_NAM_genomes.xlsx](https://github.com/HuffordLab/NAM-genomes/files/7878064/PacBio_stats_v2.1_NAM_genomes.xlsx) spreadsheet for details regarding coverage.
> > Thanks,
> 
> Hello,
> 
> What's the meaning of "processed" at subreads, it seems all the pacbio CLRs passed the QC step by SequelTools.
> 
> Thank you
> 
> Tian



> 

I download the B73 CLRs  (ERR3288278,ERR3288281,ERR3288284,ERR3288287,ERR3288290,ERR3288293,ERR3288279,ERR3288282,ERR3288285,ERR3288288,ERR3288291,ERR3288294,ERR3288280,ERR3288283,ERR3288286,ERR3288289,ERR3288292,ERR3288295), but the total bases were 195,282,635,506. 
Is it right? Is it under quality control？ How?

**Comment by aseetharam** [comment]
Hi @ttian627:

Sorry, I mislabelled them. The "Raw" is subreads, and the "Processed" is Falcon error-corrected reads.  If you look at the coverage stats, it uses the Subreads (labeled as "Raw") for calculations. This is true for all the tabs. 
Falcon error correction was performed per the instructions provided [here](https://github.com/HuffordLab/NAM-genomes/tree/master/genome-assembly#falcon-error-correction).

Thanks,

**Comment by ttian627** [comment]
Hello
The  FALOCN error corrected reads  were 32x-56x coverage described in the Supplementary Material of NAM paper, but the processed reads were larger. 
Actually, I have the following questions.
What are the downloaded data at EMBL of B73v5 (ERR3288278..etc.). The total bases were neither equal to the raw data nor the processed data.
What quality control processes did they go through？quality control with smrtlink or SequelTools?


Thank you


Tian

















At 2022-04-10 00:10:52, "Arun Seetharam" ***@***.***> wrote:

Hi @ttian627:

Sorry, I mislabelled them. The "Raw" is subreads, and the "Processed" is Falcon error-corrected reads. If you look at the coverage stats, it uses the Subreads (labeled as "Raw") for calculations. This is true for all the tabs.
Falcon error correction was performed per the instructions provided here.

Thanks,

**Comment by aseetharam** [comment]
When I sum the "Raw" reads (wrongly labeled - they are subreads), I get pretty close numbers to yours. 
![image](https://user-images.githubusercontent.com/4835524/162751206-f928306a-6236-4175-a5fb-6ec433f3f99a.png)
It could be that while downloading, you may have enabled some filtering that might have trimmed certain bases. You can calculate bases for each file and compare them to the table in the excel sheet, but I wouldn't worry about a little difference in the total count.
