### ISSUE TITLE
falcon kit version

### ISSUE THREAD

**Issue by ttian627** [HuffordLab/NAM-genomes#14]
Hello,
Where can I install the corresponding falcon kit? I can not find falcon-kit v0.7 now.

**Comment by aseetharam** [comment]
Hi @ttian627:

Thanks for getting in touch. If you are running Falcon on your assembly, we highly recommend that you use the latest version of the assembler as they have many bug fixes. If you are trying to replicate the results, then you can get the previous versions of this assembler from this [link](https://downloads.pacbcloud.com/public/falcon/). Note that the Falcon assembler is also called as `pb-assembly` and their corresponding versions are listed [here](https://github.com/PacificBiosciences/pbbioconda/wiki/Release-notes).

**Comment by ttian627** [comment]
OK, thank you!
















At 2022-02-16 22:31:56, "Arun Seetharam" ***@***.***> wrote:

Hi @ttian627:

Thanks for getting in touch. If you are running Falcon on your assembly, we highly recommend that you use the latest version of the assembler as they have many bug fixes. If you are trying to replicate the results, then you can get the previous versions of this assembler from this link. Note that the Falcon assembler is also called as pb-assembly and their corresponding versions are listed here.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ttian627** [comment]
Hello,


When I used the pb-assembly，it seems can not skip the repeat mask step with the setting "pa_HPCTANmask_option=  pa_REPmask_code=0,300;0,300;0,300". Is it right?
Thank you


Tian
















At 2022-02-16 22:31:56, "Arun Seetharam" ***@***.***> wrote:

Hi @ttian627:

Thanks for getting in touch. If you are running Falcon on your assembly, we highly recommend that you use the latest version of the assembler as they have many bug fixes. If you are trying to replicate the results, then you can get the previous versions of this assembler from this link. Note that the Falcon assembler is also called as pb-assembly and their corresponding versions are listed here.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aseetharam** [comment]
Hi @ttian627: 

I'm not sure what the correct options are for `pa_REPmask_code`. I think that would be a good question to ask the official Falcon developers (pb-assembly [GitHub](https://github.com/PacificBiosciences/pb-assembly)).

Thanks,

**Comment by aseetharam** [comment]
Hi @ttian627: 

I'm not sure what the correct options are for `pa_REPmask_code`. I think that would be a good question to ask the official Falcon developers (pb-assembly [GitHub](https://github.com/PacificBiosciences/pb-assembly)).

Thanks,

**Comment by ttian627** [comment]
Hello，


When I set the "seed_coverage=50, length_cutoff = -1" , FALCON will auto compute the cutoff. The cutoff up to 20kb, but the cns reads were only 20X at my 198G CLR data. I find the "-H10310" at "pa_HPCdaligner_option" will not effective.  Should I need set the "length_cutoff = 10000" or change to a bigger seed coverage?
Thank you!


Tian










At 2022-02-18 07:37:18, "Arun Seetharam" ***@***.***> wrote:

Closed #14.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aseetharam** [comment]
Sorry, @ttian627, can't be of much help here.

Thanks,
